### ISSUE TITLE
whats need for masking the service ?

### ISSUE THREAD

**Issue by IMXSwarup** [mrtejas99/wifi-extender#7]
hello , can any one please tell me what is the need for masking the dhcpcd service...?
actually after masking the service everything works , but just the network icon disappears( i mean no apadter shown there ) from the raspberry os...

**Comment by mrtejas99** [comment]
`dhcpcd` is a DHCP client. You can run it as a standalone service, so that it configures IP addresses on an interface. When doing that, it overlaps in functionality with what `NetworkManager`(this is responsible for the network icon)/`networkd` does. You would never use `dhcpcd` (as standalone service) on the same interface as `NetworkManager`/`networkd`. In this sense, `dhcpcd` is also a "network manager", mostly focusing on DHCP only.
